"""initial schema

Revision ID: b779219194fe
Revises: 
Create Date: 2026-08-14 18:47:06.920540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b779219194fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('job_url', sa.String(length=1024), nullable=True),
    sa.Column('raw_posting_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('current_status', sa.String(length=64), nullable=False),
    sa.Column('date_applied', sa.Date(), nullable=False),
    sa.Column('date_first_response', sa.Date(), nullable=True),
    sa.Column('salary_range_min', sa.Integer(), nullable=True),
    sa.Column('salary_range_max', sa.Integer(), nullable=True),
    sa.Column('location_type', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_company_name'), 'application', ['company_name'], unique=False)
    op.create_index(op.f('ix_application_current_status'), 'application', ['current_status'], unique=False)
    op.create_index(op.f('ix_application_date_applied'), 'application', ['date_applied'], unique=False)
    op.create_index(op.f('ix_application_location_type'), 'application', ['location_type'], unique=False)
    op.create_index(op.f('ix_application_role_title'), 'application', ['role_title'], unique=False)
    op.create_index(op.f('ix_application_source'), 'application', ['source'], unique=False)
    op.create_table('statusevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=64), nullable=True),
    sa.Column('to_status', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statusevent_application_id'), 'statusevent', ['application_id'], unique=False)
    op.create_index(op.f('ix_statusevent_timestamp'), 'statusevent', ['timestamp'], unique=False)
    op.create_index(op.f('ix_statusevent_to_status'), 'statusevent', ['to_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statusevent_to_status'), table_name='statusevent')
    op.drop_index(op.f('ix_statusevent_timestamp'), table_name='statusevent')
    op.drop_index(op.f('ix_statusevent_application_id'), table_name='statusevent')
    op.drop_table('statusevent')
    op.drop_index(op.f('ix_application_source'), table_name='application')
    op.drop_index(op.f('ix_application_role_title'), table_name='application')
    op.drop_index(op.f('ix_application_location_type'), table_name='application')
    op.drop_index(op.f('ix_application_date_applied'), table_name='application')
    op.drop_index(op.f('ix_application_current_status'), table_name='application')
    op.drop_index(op.f('ix_application_company_name'), table_name='application')
    op.drop_table('application')
    # ### end Alembic commands ###
